// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Vitalis.Infrastructure.Persistence;

#nullable disable

namespace Vitalis.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(VitalisDbContext))]
    partial class VitalisDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("Vietnamese_CI_AS")
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Vitalis.Domain.Entities.Auth.AuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("action");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("Detail")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("detail");

                    b.Property<int?>("EntityId")
                        .HasColumnType("int")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("entity_name");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("EntityName", "EntityId")
                        .HasDatabaseName("IX_audit_logs_entity");

                    b.ToTable("audit_logs", "auth");
                });

            modelBuilder.Entity("Vitalis.Domain.Entities.Auth.Permission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("permissions", "auth");
                });

            modelBuilder.Entity("Vitalis.Domain.Entities.Auth.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("DeviceInfo")
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("device_info");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("expires_at");

                    b.Property<string>("IpAddress")
                        .HasColumnType("varchar(45)")
                        .HasColumnName("ip_address");

                    b.Property<string>("ReplacedByTokenHash")
                        .HasColumnType("char(64)")
                        .HasColumnName("replaced_by_token_hash");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("revoked_at");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("char(64)")
                        .HasColumnName("token_hash");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("UX_refresh_tokens_token_hash");

                    b.HasIndex("UserId");

                    b.ToTable("refresh_tokens", "auth");
                });

            modelBuilder.Entity("Vitalis.Domain.Entities.Auth.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("description");

                    b.Property<bool>("IsSystem")
                        .HasColumnType("bit")
                        .HasColumnName("is_system");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("roles", "auth");
                });

            modelBuilder.Entity("Vitalis.Domain.Entities.Auth.RolePermission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("PermissionId")
                        .HasColumnType("int")
                        .HasColumnName("permission_id");

                    b.Property<int>("RoleId")
                        .HasColumnType("int")
                        .HasColumnName("role_id");

                    b.HasKey("Id");

                    b.HasIndex("PermissionId");

                    b.HasIndex("RoleId", "PermissionId")
                        .IsUnique()
                        .HasDatabaseName("UQ_role_permissions");

                    b.ToTable("role_permissions", "auth");
                });

            modelBuilder.Entity("Vitalis.Domain.Entities.Auth.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("varchar(500)")
                        .HasColumnName("avatar_url");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("Email")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("email");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit")
                        .HasColumnName("email_confirmed");

                    b.Property<int>("FailedLoginCount")
                        .HasColumnType("int")
                        .HasColumnName("failed_login_count");

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("full_name");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("is_deleted");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("last_login_at");

                    b.Property<DateTime?>("LockoutEnd")
                        .HasColumnType("datetime2")
                        .HasColumnName("lockout_end");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Phone")
                        .HasColumnType("varchar(20)")
                        .HasColumnName("phone");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("UX_users_email")
                        .HasFilter("[email] IS NOT NULL");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("users", "auth", t =>
                        {
                            t.HasCheckConstraint("CK_users_failed_login_count", "failed_login_count >= 0");
                        });
                });

            modelBuilder.Entity("Vitalis.Domain.Entities.Auth.UserRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AssignedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("assigned_at")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<int?>("AssignedBy")
                        .HasColumnType("int")
                        .HasColumnName("assigned_by");

                    b.Property<int>("RoleId")
                        .HasColumnType("int")
                        .HasColumnName("role_id");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("AssignedBy");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId", "RoleId")
                        .IsUnique()
                        .HasDatabaseName("UQ_user_roles");

                    b.ToTable("user_roles", "auth");
                });

            modelBuilder.Entity("Vitalis.Domain.Entities.Billing.InsurancePolicy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("CoveragePercent")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("coverage_percent");

                    b.Property<int>("PatientId")
                        .HasColumnType("int")
                        .HasColumnName("patient_id");

                    b.Property<string>("PolicyNumber")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("policy_number");

                    b.Property<string>("Provider")
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("provider");

                    b.Property<DateOnly?>("ValidFrom")
                        .HasColumnType("date")
                        .HasColumnName("valid_from");

                    b.Property<DateOnly?>("ValidTo")
                        .HasColumnType("date")
                        .HasColumnName("valid_to");

                    b.HasKey("Id");

                    b.HasIndex("PatientId");

                    b.HasIndex("PolicyNumber")
                        .IsUnique()
                        .HasDatabaseName("UX_insurance_policies_policy_number");

                    b.ToTable("insurance_policies", "billing", t =>
                        {
                            t.HasCheckConstraint("CK_insurance_policies_coverage", "coverage_percent IS NULL OR coverage_percent BETWEEN 0 AND 100");
                        });
                });

            modelBuilder.Entity("Vitalis.Domain.Entities.Billing.Invoice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AppointmentId")
                        .HasColumnType("int")
                        .HasColumnName("appointment_id");

                    b.Property<string>("CancelReason")
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("cancel_reason");

                    b.Property<DateTime?>("CancelledAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("cancelled_at");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int")
                        .HasColumnName("created_by");

                    b.Property<decimal>("DiscountAmount")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("discount_amount");

                    b.Property<decimal>("InsuranceAmount")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("insurance_amount");

                    b.Property<string>("InvoiceNo")
                        .HasColumnType("varchar(30)")
                        .HasColumnName("invoice_no");

                    b.Property<int?>("MedicalRecordId")
                        .HasColumnType("int")
                        .HasColumnName("medical_record_id");

                    b.Property<decimal>("PaidAmount")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("paid_amount");

                    b.Property<int>("PatientId")
                        .HasColumnType("int")
                        .HasColumnName("patient_id");

                    b.Property<string>("PatientName")
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("patient_name");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint")
                        .HasColumnName("status");

                    b.Property<decimal>("TaxAmount")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("tax_amount");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("total_amount");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("AppointmentId");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("InvoiceNo")
                        .IsUnique()
                        .HasDatabaseName("UX_invoices_invoice_no")
                        .HasFilter("[invoice_no] IS NOT NULL");

                    b.HasIndex("MedicalRecordId");

                    b.HasIndex("PatientId");

                    b.HasIndex("Status", "CreatedAt")
                        .HasDatabaseName("IX_invoices_status_created_at");

                    b.ToTable("invoices", "billing", t =>
                        {
                            t.HasCheckConstraint("CK_invoices_discount_non_negative", "discount_amount >= 0");

                            t.HasCheckConstraint("CK_invoices_insurance_non_negative", "insurance_amount >= 0");

                            t.HasCheckConstraint("CK_invoices_paid_non_negative", "paid_amount >= 0");

                            t.HasCheckConstraint("CK_invoices_status", "status BETWEEN 0 AND 2");

                            t.HasCheckConstraint("CK_invoices_tax_non_negative", "tax_amount >= 0");

                            t.HasCheckConstraint("CK_invoices_total_non_negative", "total_amount >= 0");
                        });
                });

            modelBuilder.Entity("Vitalis.Domain.Entities.Billing.InvoiceItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("amount");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("description");

                    b.Property<decimal>("DiscountAmount")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("discount_amount");

                    b.Property<int>("InvoiceId")
                        .HasColumnType("int")
                        .HasColumnName("invoice_id");

                    b.Property<int?>("MedicalRecordServiceId")
                        .HasColumnType("int")
                        .HasColumnName("medical_record_service_id");

                    b.Property<int?>("MedicineId")
                        .HasColumnType("int")
                        .HasColumnName("medicine_id");

                    b.Property<int>("Quantity")
                        .HasColumnType("int")
                        .HasColumnName("quantity");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("unit_price");

                    b.HasKey("Id");

                    b.HasIndex("InvoiceId");

                    b.HasIndex("MedicalRecordServiceId");

                    b.HasIndex("MedicineId");

                    b.ToTable("invoice_items", "billing", t =>
                        {
                            t.HasCheckConstraint("CK_invoice_items_amount", "amount >= 0");

                            t.HasCheckConstraint("CK_invoice_items_at_most_one_ref", "(CASE WHEN medical_record_service_id IS NOT NULL THEN 1 ELSE 0 END) + (CASE WHEN medicine_id IS NOT NULL THEN 1 ELSE 0 END) <= 1");

                            t.HasCheckConstraint("CK_invoice_items_discount", "discount_amount >= 0");

                            t.HasCheckConstraint("CK_invoice_items_quantity", "quantity > 0");
                        });
                });

            modelBuilder.Entity("Vitalis.Domain.Entities.Billing.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("amount");

                    b.Property<int>("InvoiceId")
                        .HasColumnType("int")
                        .HasColumnName("invoice_id");

                    b.Property<bool>("IsRefund")
                        .HasColumnType("bit")
                        .HasColumnName("is_refund");

                    b.Property<byte>("Method")
                        .HasColumnType("tinyint")
                        .HasColumnName("method");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("note");

                    b.Property<DateTime>("PaidAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("paid_at")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<int?>("ReceivedBy")
                        .HasColumnType("int")
                        .HasColumnName("received_by");

                    b.Property<string>("ReferenceCode")
                        .HasColumnType("varchar(100)")
                        .HasColumnName("reference_code");

                    b.HasKey("Id");

                    b.HasIndex("InvoiceId");

                    b.HasIndex("ReceivedBy");

                    b.ToTable("payments", "billing", t =>
                        {
                            t.HasCheckConstraint("CK_payments_amount_sign", "(is_refund = 0 AND amount > 0) OR (is_refund = 1 AND amount < 0)");

                            t.HasCheckConstraint("CK_payments_method", "method BETWEEN 0 AND 3");
                        });
                });

            modelBuilder.Entity("Vitalis.Domain.Entities.Billing.Service", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .HasColumnType("varchar(20)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("description");

                    b.Property<int?>("DurationMinutes")
                        .HasColumnType("int")
                        .HasColumnName("duration_minutes");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("name");

                    b.Property<decimal>("Price")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("price");

                    b.Property<int?>("SpecialtyId")
                        .HasColumnType("int")
                        .HasColumnName("specialty_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("UX_services_code")
                        .HasFilter("[code] IS NOT NULL");

                    b.HasIndex("SpecialtyId");

                    b.ToTable("services", "billing", t =>
                        {
                            t.HasCheckConstraint("CK_services_price", "price >= 0");
                        });
                });

            modelBuilder.Entity("Vitalis.Domain.Entities.Clinical.Attachment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FileType")
                        .HasColumnType("varchar(50)")
                        .HasColumnName("file_type");

                    b.Property<string>("FileUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("file_url");

                    b.Property<int>("MedicalRecordId")
                        .HasColumnType("int")
                        .HasColumnName("medical_record_id");

                    b.Property<DateTime>("UploadedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("uploaded_at")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.HasKey("Id");

                    b.HasIndex("MedicalRecordId");

                    b.ToTable("attachments", "clinical");
                });

            modelBuilder.Entity("Vitalis.Domain.Entities.Clinical.LabResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Conclusion")
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("conclusion");

                    b.Property<int>("MedicalRecordServiceId")
                        .HasColumnType("int")
                        .HasColumnName("medical_record_service_id");

                    b.Property<string>("ReferenceRange")
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("reference_range");

                    b.Property<string>("ResultValue")
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("result_value");

                    b.Property<DateTime?>("ResultedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("resulted_at");

                    b.HasKey("Id");

                    b.HasIndex("MedicalRecordServiceId")
                        .HasDatabaseName("IX_lab_results_mrs_id");

                    b.ToTable("lab_results", "clinical");
                });

            modelBuilder.Entity("Vitalis.Domain.Entities.Clinical.MedicalRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AppointmentId")
                        .HasColumnType("int")
                        .HasColumnName("appointment_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("Diagnosis")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("diagnosis");

                    b.Property<int>("DoctorId")
                        .HasColumnType("int")
                        .HasColumnName("doctor_id");

                    b.Property<DateTime?>("FinalizedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("finalized_at");

                    b.Property<DateOnly?>("FollowUpDate")
                        .HasColumnType("date")
                        .HasColumnName("follow_up_date");

                    b.Property<string>("Icd10Code")
                        .HasColumnType("varchar(10)")
                        .HasColumnName("icd10_code");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("note");

                    b.Property<int>("PatientId")
                        .HasColumnType("int")
                        .HasColumnName("patient_id");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint")
                        .HasColumnName("status");

                    b.Property<string>("Symptoms")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("symptoms");

                    b.Property<string>("TreatmentPlan")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("treatment_plan");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("AppointmentId")
                        .IsUnique();

                    b.HasIndex("DoctorId");

                    b.HasIndex("PatientId");

                    b.ToTable("medical_records", "clinical", t =>
                        {
                            t.HasCheckConstraint("CK_medical_records_status", "status BETWEEN 0 AND 1");
                        });
                });

            modelBuilder.Entity("Vitalis.Domain.Entities.Clinical.MedicalRecordService", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("MedicalRecordId")
                        .HasColumnType("int")
                        .HasColumnName("medical_record_id");

                    b.Property<DateTime>("OrderedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("ordered_at")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<int?>("PerformedBy")
                        .HasColumnType("int")
                        .HasColumnName("performed_by");

                    b.Property<int>("Quantity")
                        .HasColumnType("int")
                        .HasColumnName("quantity");

                    b.Property<int>("ServiceId")
                        .HasColumnType("int")
                        .HasColumnName("service_id");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint")
                        .HasColumnName("status");

                    b.Property<decimal>("UnitPriceSnapshot")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("unit_price_snapshot");

                    b.HasKey("Id");

                    b.HasIndex("PerformedBy");

                    b.HasIndex("ServiceId");

                    b.HasIndex("MedicalRecordId", "Status")
                        .HasDatabaseName("IX_mrs_medical_record_status");

                    b.ToTable("medical_record_services", "clinical", t =>
                        {
                            t.HasCheckConstraint("CK_mrs_quantity", "quantity > 0");

                            t.HasCheckConstraint("CK_mrs_status", "status BETWEEN 0 AND 3");

                            t.HasCheckConstraint("CK_mrs_unit_price", "unit_price_snapshot >= 0");
                        });
                });

            modelBuilder.Entity("Vitalis.Domain.Entities.Clinical.Medicine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ActiveIngredient")
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("active_ingredient");

                    b.Property<string>("Code")
                        .HasColumnType("varchar(30)")
                        .HasColumnName("code");

                    b.Property<string>("Concentration")
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("concentration");

                    b.Property<decimal?>("CostPrice")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("cost_price");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<int?>("MinStock")
                        .HasColumnType("int")
                        .HasColumnName("min_stock");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("name");

                    b.Property<decimal>("Price")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("price");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("int")
                        .HasColumnName("stock_quantity");

                    b.Property<string>("Unit")
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("unit");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("UX_medicines_code")
                        .HasFilter("[code] IS NOT NULL");

                    b.ToTable("medicines", "clinical", t =>
                        {
                            t.HasCheckConstraint("CK_medicines_price", "price >= 0");

                            t.HasCheckConstraint("CK_medicines_stock_non_negative", "stock_quantity >= 0");
                        });
                });

            modelBuilder.Entity("Vitalis.Domain.Entities.Clinical.MedicineBatch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BatchNo")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("batch_no");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<DateOnly>("ExpiryDate")
                        .HasColumnType("date")
                        .HasColumnName("expiry_date");

                    b.Property<decimal?>("ImportPrice")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("import_price");

                    b.Property<int>("MedicineId")
                        .HasColumnType("int")
                        .HasColumnName("medicine_id");

                    b.Property<int>("Quantity")
                        .HasColumnType("int")
                        .HasColumnName("quantity");

                    b.HasKey("Id");

                    b.HasIndex("ExpiryDate")
                        .HasDatabaseName("IX_medicine_batches_expiry_date");

                    b.HasIndex("MedicineId", "BatchNo")
                        .IsUnique()
                        .HasDatabaseName("UX_medicine_batches_medicine_batch_no");

                    b.ToTable("medicine_batches", "clinical", t =>
                        {
                            t.HasCheckConstraint("CK_medicine_batches_quantity", "quantity >= 0");
                        });
                });

            modelBuilder.Entity("Vitalis.Domain.Entities.Clinical.MedicineStockTransaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BatchId")
                        .HasColumnType("int")
                        .HasColumnName("batch_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int")
                        .HasColumnName("created_by");

                    b.Property<int>("MedicineId")
                        .HasColumnType("int")
                        .HasColumnName("medicine_id");

                    b.Property<int?>("PrescriptionId")
                        .HasColumnType("int")
                        .HasColumnName("prescription_id");

                    b.Property<int>("Quantity")
                        .HasColumnType("int")
                        .HasColumnName("quantity");

                    b.Property<byte>("Type")
                        .HasColumnType("tinyint")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("BatchId");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("MedicineId");

                    b.HasIndex("PrescriptionId");

                    b.ToTable("medicine_stock_transactions", "clinical", t =>
                        {
                            t.HasCheckConstraint("CK_mst_quantity", "quantity > 0");

                            t.HasCheckConstraint("CK_mst_type", "type BETWEEN 0 AND 2");
                        });
                });

            modelBuilder.Entity("Vitalis.Domain.Entities.Clinical.PatientAllergy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Allergen")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("allergen");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("note");

                    b.Property<int>("PatientId")
                        .HasColumnType("int")
                        .HasColumnName("patient_id");

                    b.Property<byte?>("Severity")
                        .HasColumnType("tinyint")
                        .HasColumnName("severity");

                    b.HasKey("Id");

                    b.HasIndex("PatientId");

                    b.ToTable("patient_allergies", "clinical", t =>
                        {
                            t.HasCheckConstraint("CK_patient_allergies_severity", "severity BETWEEN 0 AND 2");
                        });
                });

            modelBuilder.Entity("Vitalis.Domain.Entities.Clinical.PatientVitals", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BloodPressure")
                        .HasColumnType("varchar(20)")
                        .HasColumnName("blood_pressure");

                    b.Property<decimal?>("Height")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("height");

                    b.Property<int>("MedicalRecordId")
                        .HasColumnType("int")
                        .HasColumnName("medical_record_id");

                    b.Property<int?>("Pulse")
                        .HasColumnType("int")
                        .HasColumnName("pulse");

                    b.Property<decimal?>("Temperature")
                        .HasPrecision(4, 1)
                        .HasColumnType("decimal(4,1)")
                        .HasColumnName("temperature");

                    b.Property<decimal?>("Weight")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("weight");

                    b.HasKey("Id");

                    b.HasIndex("MedicalRecordId")
                        .IsUnique();

                    b.ToTable("patient_vitals", "clinical");
                });

            modelBuilder.Entity("Vitalis.Domain.Entities.Clinical.Prescription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<DateTime?>("DispensedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("dispensed_at");

                    b.Property<int?>("DispensedBy")
                        .HasColumnType("int")
                        .HasColumnName("dispensed_by");

                    b.Property<int>("DoctorId")
                        .HasColumnType("int")
                        .HasColumnName("doctor_id");

                    b.Property<int>("MedicalRecordId")
                        .HasColumnType("int")
                        .HasColumnName("medical_record_id");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("note");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("DispensedBy");

                    b.HasIndex("DoctorId");

                    b.HasIndex("MedicalRecordId")
                        .IsUnique();

                    b.ToTable("prescriptions", "clinical", t =>
                        {
                            t.HasCheckConstraint("CK_prescriptions_status", "status BETWEEN 0 AND 1");
                        });
                });

            modelBuilder.Entity("Vitalis.Domain.Entities.Clinical.PrescriptionItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Dosage")
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("dosage");

                    b.Property<int?>("DurationDays")
                        .HasColumnType("int")
                        .HasColumnName("duration_days");

                    b.Property<string>("Frequency")
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("frequency");

                    b.Property<string>("Instruction")
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("instruction");

                    b.Property<int>("MedicineId")
                        .HasColumnType("int")
                        .HasColumnName("medicine_id");

                    b.Property<string>("MedicineNameSnapshot")
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("medicine_name_snapshot");

                    b.Property<int>("PrescriptionId")
                        .HasColumnType("int")
                        .HasColumnName("prescription_id");

                    b.Property<int>("Quantity")
                        .HasColumnType("int")
                        .HasColumnName("quantity");

                    b.Property<decimal?>("UnitPriceSnapshot")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("unit_price_snapshot");

                    b.HasKey("Id");

                    b.HasIndex("MedicineId");

                    b.HasIndex("PrescriptionId");

                    b.ToTable("prescription_items", "clinical", t =>
                        {
                            t.HasCheckConstraint("CK_prescription_items_quantity", "quantity > 0");
                        });
                });

            modelBuilder.Entity("Vitalis.Domain.Entities.Scheduling.Appointment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AppointmentCode")
                        .HasColumnType("varchar(20)")
                        .HasColumnName("appointment_code");

                    b.Property<string>("CancelReason")
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("cancel_reason");

                    b.Property<DateTime?>("CheckedInAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("checked_in_at");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("completed_at");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int")
                        .HasColumnName("created_by");

                    b.Property<int>("DoctorId")
                        .HasColumnType("int")
                        .HasColumnName("doctor_id");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("end_time");

                    b.Property<decimal?>("FeeSnapshot")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("fee_snapshot");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("note");

                    b.Property<int>("PatientId")
                        .HasColumnType("int")
                        .HasColumnName("patient_id");

                    b.Property<int?>("QueueNumber")
                        .HasColumnType("int")
                        .HasColumnName("queue_number");

                    b.Property<string>("Reason")
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("reason");

                    b.Property<byte>("Source")
                        .HasColumnType("tinyint")
                        .HasColumnName("source");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("start_time");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("AppointmentCode")
                        .IsUnique()
                        .HasDatabaseName("UX_appointments_code")
                        .HasFilter("[appointment_code] IS NOT NULL");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("PatientId");

                    b.HasIndex("StartTime");

                    b.HasIndex("DoctorId", "StartTime")
                        .IsUnique()
                        .HasDatabaseName("UX_appointments_doctor_slot")
                        .HasFilter("[status] < 5");

                    b.ToTable("appointments", "scheduling", t =>
                        {
                            t.HasCheckConstraint("CK_appointments_fee_snapshot", "fee_snapshot IS NULL OR fee_snapshot >= 0");

                            t.HasCheckConstraint("CK_appointments_source", "source BETWEEN 0 AND 2");

                            t.HasCheckConstraint("CK_appointments_status", "status BETWEEN 0 AND 6");

                            t.HasCheckConstraint("CK_appointments_time", "end_time > start_time");
                        });
                });

            modelBuilder.Entity("Vitalis.Domain.Entities.Scheduling.AppointmentStatusHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AppointmentId")
                        .HasColumnType("int")
                        .HasColumnName("appointment_id");

                    b.Property<DateTime>("ChangedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("changed_at")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<int?>("ChangedBy")
                        .HasColumnType("int")
                        .HasColumnName("changed_by");

                    b.Property<byte?>("FromStatus")
                        .HasColumnType("tinyint")
                        .HasColumnName("from_status");

                    b.Property<string>("Reason")
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("reason");

                    b.Property<byte>("ToStatus")
                        .HasColumnType("tinyint")
                        .HasColumnName("to_status");

                    b.HasKey("Id");

                    b.HasIndex("AppointmentId")
                        .HasDatabaseName("IX_status_history_appointment_id");

                    b.HasIndex("ChangedBy");

                    b.ToTable("appointment_status_history", "scheduling", t =>
                        {
                            t.HasCheckConstraint("CK_status_history_from_status", "from_status BETWEEN 0 AND 6");

                            t.HasCheckConstraint("CK_status_history_to_status", "to_status BETWEEN 0 AND 6");
                        });
                });

            modelBuilder.Entity("Vitalis.Domain.Entities.Scheduling.Doctor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("varchar(500)")
                        .HasColumnName("avatar_url");

                    b.Property<string>("Bio")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("bio");

                    b.Property<decimal?>("ConsultationFee")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("consultation_fee");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("Email")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("email");

                    b.Property<int?>("ExperienceYears")
                        .HasColumnType("int")
                        .HasColumnName("experience_years");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("full_name");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<string>("LicenseNumber")
                        .HasColumnType("varchar(50)")
                        .HasColumnName("license_number");

                    b.Property<int?>("MaxPatientsPerDay")
                        .HasColumnType("int")
                        .HasColumnName("max_patients_per_day");

                    b.Property<string>("Phone")
                        .HasColumnType("varchar(20)")
                        .HasColumnName("phone");

                    b.Property<string>("Room")
                        .HasColumnType("varchar(50)")
                        .HasColumnName("room");

                    b.Property<int>("SpecialtyId")
                        .HasColumnType("int")
                        .HasColumnName("specialty_id");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("title");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("LicenseNumber")
                        .IsUnique()
                        .HasDatabaseName("UX_doctors_license_number")
                        .HasFilter("[license_number] IS NOT NULL");

                    b.HasIndex("SpecialtyId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("doctors", "scheduling", t =>
                        {
                            t.HasCheckConstraint("CK_doctors_consultation_fee", "consultation_fee IS NULL OR consultation_fee >= 0");
                        });
                });

            modelBuilder.Entity("Vitalis.Domain.Entities.Scheduling.DoctorSchedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<TimeOnly?>("BreakEnd")
                        .HasColumnType("time")
                        .HasColumnName("break_end");

                    b.Property<TimeOnly?>("BreakStart")
                        .HasColumnType("time")
                        .HasColumnName("break_start");

                    b.Property<byte>("DayOfWeek")
                        .HasColumnType("tinyint")
                        .HasColumnName("day_of_week");

                    b.Property<int>("DoctorId")
                        .HasColumnType("int")
                        .HasColumnName("doctor_id");

                    b.Property<DateOnly>("EffectiveFrom")
                        .HasColumnType("date")
                        .HasColumnName("effective_from");

                    b.Property<DateOnly?>("EffectiveTo")
                        .HasColumnType("date")
                        .HasColumnName("effective_to");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time")
                        .HasColumnName("end_time");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<int>("SlotMinutes")
                        .HasColumnType("int")
                        .HasColumnName("slot_minutes");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time")
                        .HasColumnName("start_time");

                    b.HasKey("Id");

                    b.HasIndex("DoctorId");

                    b.HasIndex("DoctorId", "DayOfWeek", "StartTime")
                        .IsUnique()
                        .HasDatabaseName("UX_doctor_schedules_slot");

                    b.ToTable("doctor_schedules", "scheduling", t =>
                        {
                            t.HasCheckConstraint("CK_doctor_schedules_break", "(break_start IS NULL AND break_end IS NULL) OR (break_end > break_start)");

                            t.HasCheckConstraint("CK_doctor_schedules_day_of_week", "day_of_week BETWEEN 0 AND 6");

                            t.HasCheckConstraint("CK_doctor_schedules_effective", "effective_to IS NULL OR effective_to > effective_from");

                            t.HasCheckConstraint("CK_doctor_schedules_time", "end_time > start_time");
                        });
                });

            modelBuilder.Entity("Vitalis.Domain.Entities.Scheduling.DoctorTimeOff", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ApprovedBy")
                        .HasColumnType("int")
                        .HasColumnName("approved_by");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<int?>("DoctorId")
                        .HasColumnType("int")
                        .HasColumnName("doctor_id");

                    b.Property<DateTime>("EndAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("end_at");

                    b.Property<bool>("IsFullDay")
                        .HasColumnType("bit")
                        .HasColumnName("is_full_day");

                    b.Property<string>("Reason")
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("reason");

                    b.Property<DateTime>("StartAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("start_at");

                    b.Property<byte>("Type")
                        .HasColumnType("tinyint")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("ApprovedBy");

                    b.HasIndex("DoctorId", "StartAt")
                        .HasDatabaseName("IX_doctor_time_off_doctor_start");

                    b.ToTable("doctor_time_off", "scheduling", t =>
                        {
                            t.HasCheckConstraint("CK_doctor_time_off_time", "end_at > start_at");

                            t.HasCheckConstraint("CK_doctor_time_off_type", "type BETWEEN 0 AND 2");
                        });
                });

            modelBuilder.Entity("Vitalis.Domain.Entities.Scheduling.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AppointmentId")
                        .HasColumnType("int")
                        .HasColumnName("appointment_id");

                    b.Property<byte>("Channel")
                        .HasColumnType("tinyint")
                        .HasColumnName("channel");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<DateTime?>("SentAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("sent_at");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("AppointmentId");

                    b.ToTable("notifications", "scheduling", t =>
                        {
                            t.HasCheckConstraint("CK_notifications_channel", "channel BETWEEN 0 AND 2");

                            t.HasCheckConstraint("CK_notifications_status", "status BETWEEN 0 AND 2");
                        });
                });

            modelBuilder.Entity("Vitalis.Domain.Entities.Scheduling.Patient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("address");

                    b.Property<string>("BloodType")
                        .HasColumnType("varchar(5)")
                        .HasColumnName("blood_type");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<DateOnly?>("DateOfBirth")
                        .HasColumnType("date")
                        .HasColumnName("date_of_birth");

                    b.Property<string>("Email")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("email");

                    b.Property<string>("EmergencyContactName")
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("emergency_contact_name");

                    b.Property<string>("EmergencyContactPhone")
                        .HasColumnType("varchar(20)")
                        .HasColumnName("emergency_contact_phone");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("full_name");

                    b.Property<byte?>("Gender")
                        .HasColumnType("tinyint")
                        .HasColumnName("gender");

                    b.Property<string>("InsuranceNumber")
                        .HasColumnType("varchar(20)")
                        .HasColumnName("insurance_number");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<string>("NationalId")
                        .HasColumnType("varchar(20)")
                        .HasColumnName("national_id");

                    b.Property<string>("PatientCode")
                        .HasColumnType("varchar(20)")
                        .HasColumnName("patient_code");

                    b.Property<string>("Phone")
                        .HasColumnType("varchar(20)")
                        .HasColumnName("phone");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("FullName");

                    b.HasIndex("PatientCode")
                        .IsUnique()
                        .HasDatabaseName("UX_patients_patient_code")
                        .HasFilter("[patient_code] IS NOT NULL");

                    b.HasIndex("Phone");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("UX_patients_user_id")
                        .HasFilter("[user_id] IS NOT NULL");

                    b.ToTable("patients", "scheduling", t =>
                        {
                            t.HasCheckConstraint("CK_patients_gender", "gender BETWEEN 0 AND 2");
                        });
                });

            modelBuilder.Entity("Vitalis.Domain.Entities.Scheduling.Specialty", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .HasColumnType("varchar(20)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("name");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("UX_specialties_code")
                        .HasFilter("[code] IS NOT NULL");

                    b.ToTable("specialties", "scheduling");
                });

            modelBuilder.Entity("Vitalis.Domain.Entities.Auth.AuditLog", b =>
                {
                    b.HasOne("Vitalis.Domain.Entities.Auth.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("User");
                });

            modelBuilder.Entity("Vitalis.Domain.Entities.Auth.RefreshToken", b =>
                {
                    b.HasOne("Vitalis.Domain.Entities.Auth.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Vitalis.Domain.Entities.Auth.RolePermission", b =>
                {
                    b.HasOne("Vitalis.Domain.Entities.Auth.Permission", "Permission")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Vitalis.Domain.Entities.Auth.Role", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Vitalis.Domain.Entities.Auth.UserRole", b =>
                {
                    b.HasOne("Vitalis.Domain.Entities.Auth.User", "AssignedByUser")
                        .WithMany()
                        .HasForeignKey("AssignedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Vitalis.Domain.Entities.Auth.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Vitalis.Domain.Entities.Auth.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssignedByUser");

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Vitalis.Domain.Entities.Billing.InsurancePolicy", b =>
                {
                    b.HasOne("Vitalis.Domain.Entities.Scheduling.Patient", "Patient")
                        .WithMany("InsurancePolicies")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("Vitalis.Domain.Entities.Billing.Invoice", b =>
                {
                    b.HasOne("Vitalis.Domain.Entities.Scheduling.Appointment", "Appointment")
                        .WithMany()
                        .HasForeignKey("AppointmentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Vitalis.Domain.Entities.Auth.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Vitalis.Domain.Entities.Clinical.MedicalRecord", "MedicalRecord")
                        .WithMany()
                        .HasForeignKey("MedicalRecordId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Vitalis.Domain.Entities.Scheduling.Patient", "Patient")
                        .WithMany()
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Appointment");

                    b.Navigation("CreatedByUser");

                    b.Navigation("MedicalRecord");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("Vitalis.Domain.Entities.Billing.InvoiceItem", b =>
                {
                    b.HasOne("Vitalis.Domain.Entities.Billing.Invoice", "Invoice")
                        .WithMany("Items")
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Vitalis.Domain.Entities.Clinical.MedicalRecordService", "MedicalRecordService")
                        .WithMany()
                        .HasForeignKey("MedicalRecordServiceId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Vitalis.Domain.Entities.Clinical.Medicine", "Medicine")
                        .WithMany()
                        .HasForeignKey("MedicineId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Invoice");

                    b.Navigation("MedicalRecordService");

                    b.Navigation("Medicine");
                });

            modelBuilder.Entity("Vitalis.Domain.Entities.Billing.Payment", b =>
                {
                    b.HasOne("Vitalis.Domain.Entities.Billing.Invoice", "Invoice")
                        .WithMany("Payments")
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Vitalis.Domain.Entities.Auth.User", "ReceivedByUser")
                        .WithMany()
                        .HasForeignKey("ReceivedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Invoice");

                    b.Navigation("ReceivedByUser");
                });

            modelBuilder.Entity("Vitalis.Domain.Entities.Billing.Service", b =>
                {
                    b.HasOne("Vitalis.Domain.Entities.Scheduling.Specialty", "Specialty")
                        .WithMany()
                        .HasForeignKey("SpecialtyId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Specialty");
                });

            modelBuilder.Entity("Vitalis.Domain.Entities.Clinical.Attachment", b =>
                {
                    b.HasOne("Vitalis.Domain.Entities.Clinical.MedicalRecord", "MedicalRecord")
                        .WithMany("Attachments")
                        .HasForeignKey("MedicalRecordId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("MedicalRecord");
                });

            modelBuilder.Entity("Vitalis.Domain.Entities.Clinical.LabResult", b =>
                {
                    b.HasOne("Vitalis.Domain.Entities.Clinical.MedicalRecordService", "MedicalRecordService")
                        .WithMany("LabResults")
                        .HasForeignKey("MedicalRecordServiceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("MedicalRecordService");
                });

            modelBuilder.Entity("Vitalis.Domain.Entities.Clinical.MedicalRecord", b =>
                {
                    b.HasOne("Vitalis.Domain.Entities.Scheduling.Appointment", "Appointment")
                        .WithOne()
                        .HasForeignKey("Vitalis.Domain.Entities.Clinical.MedicalRecord", "AppointmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Vitalis.Domain.Entities.Scheduling.Doctor", "Doctor")
                        .WithMany()
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Vitalis.Domain.Entities.Scheduling.Patient", "Patient")
                        .WithMany()
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Appointment");

                    b.Navigation("Doctor");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("Vitalis.Domain.Entities.Clinical.MedicalRecordService", b =>
                {
                    b.HasOne("Vitalis.Domain.Entities.Clinical.MedicalRecord", "MedicalRecord")
                        .WithMany("Services")
                        .HasForeignKey("MedicalRecordId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Vitalis.Domain.Entities.Auth.User", "PerformedByUser")
                        .WithMany()
                        .HasForeignKey("PerformedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Vitalis.Domain.Entities.Billing.Service", "Service")
                        .WithMany()
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("MedicalRecord");

                    b.Navigation("PerformedByUser");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("Vitalis.Domain.Entities.Clinical.MedicineBatch", b =>
                {
                    b.HasOne("Vitalis.Domain.Entities.Clinical.Medicine", "Medicine")
                        .WithMany("Batches")
                        .HasForeignKey("MedicineId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Medicine");
                });

            modelBuilder.Entity("Vitalis.Domain.Entities.Clinical.MedicineStockTransaction", b =>
                {
                    b.HasOne("Vitalis.Domain.Entities.Clinical.MedicineBatch", "Batch")
                        .WithMany()
                        .HasForeignKey("BatchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Vitalis.Domain.Entities.Auth.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Vitalis.Domain.Entities.Clinical.Medicine", "Medicine")
                        .WithMany()
                        .HasForeignKey("MedicineId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Vitalis.Domain.Entities.Clinical.Prescription", "Prescription")
                        .WithMany()
                        .HasForeignKey("PrescriptionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Batch");

                    b.Navigation("CreatedByUser");

                    b.Navigation("Medicine");

                    b.Navigation("Prescription");
                });

            modelBuilder.Entity("Vitalis.Domain.Entities.Clinical.PatientAllergy", b =>
                {
                    b.HasOne("Vitalis.Domain.Entities.Scheduling.Patient", "Patient")
                        .WithMany("Allergies")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("Vitalis.Domain.Entities.Clinical.PatientVitals", b =>
                {
                    b.HasOne("Vitalis.Domain.Entities.Clinical.MedicalRecord", "MedicalRecord")
                        .WithOne("Vitals")
                        .HasForeignKey("Vitalis.Domain.Entities.Clinical.PatientVitals", "MedicalRecordId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("MedicalRecord");
                });

            modelBuilder.Entity("Vitalis.Domain.Entities.Clinical.Prescription", b =>
                {
                    b.HasOne("Vitalis.Domain.Entities.Auth.User", "DispensedByUser")
                        .WithMany()
                        .HasForeignKey("DispensedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Vitalis.Domain.Entities.Scheduling.Doctor", "Doctor")
                        .WithMany()
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Vitalis.Domain.Entities.Clinical.MedicalRecord", "MedicalRecord")
                        .WithOne("Prescription")
                        .HasForeignKey("Vitalis.Domain.Entities.Clinical.Prescription", "MedicalRecordId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DispensedByUser");

                    b.Navigation("Doctor");

                    b.Navigation("MedicalRecord");
                });

            modelBuilder.Entity("Vitalis.Domain.Entities.Clinical.PrescriptionItem", b =>
                {
                    b.HasOne("Vitalis.Domain.Entities.Clinical.Medicine", "Medicine")
                        .WithMany()
                        .HasForeignKey("MedicineId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Vitalis.Domain.Entities.Clinical.Prescription", "Prescription")
                        .WithMany("Items")
                        .HasForeignKey("PrescriptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Medicine");

                    b.Navigation("Prescription");
                });

            modelBuilder.Entity("Vitalis.Domain.Entities.Scheduling.Appointment", b =>
                {
                    b.HasOne("Vitalis.Domain.Entities.Auth.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Vitalis.Domain.Entities.Scheduling.Doctor", "Doctor")
                        .WithMany()
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Vitalis.Domain.Entities.Scheduling.Patient", "Patient")
                        .WithMany()
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedByUser");

                    b.Navigation("Doctor");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("Vitalis.Domain.Entities.Scheduling.AppointmentStatusHistory", b =>
                {
                    b.HasOne("Vitalis.Domain.Entities.Scheduling.Appointment", "Appointment")
                        .WithMany("StatusHistory")
                        .HasForeignKey("AppointmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Vitalis.Domain.Entities.Auth.User", "ChangedByUser")
                        .WithMany()
                        .HasForeignKey("ChangedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Appointment");

                    b.Navigation("ChangedByUser");
                });

            modelBuilder.Entity("Vitalis.Domain.Entities.Scheduling.Doctor", b =>
                {
                    b.HasOne("Vitalis.Domain.Entities.Scheduling.Specialty", "Specialty")
                        .WithMany("Doctors")
                        .HasForeignKey("SpecialtyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Vitalis.Domain.Entities.Auth.User", "User")
                        .WithOne()
                        .HasForeignKey("Vitalis.Domain.Entities.Scheduling.Doctor", "UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Specialty");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Vitalis.Domain.Entities.Scheduling.DoctorSchedule", b =>
                {
                    b.HasOne("Vitalis.Domain.Entities.Scheduling.Doctor", "Doctor")
                        .WithMany("Schedules")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Doctor");
                });

            modelBuilder.Entity("Vitalis.Domain.Entities.Scheduling.DoctorTimeOff", b =>
                {
                    b.HasOne("Vitalis.Domain.Entities.Auth.User", "ApprovedByUser")
                        .WithMany()
                        .HasForeignKey("ApprovedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Vitalis.Domain.Entities.Scheduling.Doctor", "Doctor")
                        .WithMany()
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ApprovedByUser");

                    b.Navigation("Doctor");
                });

            modelBuilder.Entity("Vitalis.Domain.Entities.Scheduling.Notification", b =>
                {
                    b.HasOne("Vitalis.Domain.Entities.Scheduling.Appointment", "Appointment")
                        .WithMany()
                        .HasForeignKey("AppointmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Appointment");
                });

            modelBuilder.Entity("Vitalis.Domain.Entities.Scheduling.Patient", b =>
                {
                    b.HasOne("Vitalis.Domain.Entities.Auth.User", "User")
                        .WithOne()
                        .HasForeignKey("Vitalis.Domain.Entities.Scheduling.Patient", "UserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("User");
                });

            modelBuilder.Entity("Vitalis.Domain.Entities.Auth.Permission", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("Vitalis.Domain.Entities.Auth.Role", b =>
                {
                    b.Navigation("RolePermissions");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("Vitalis.Domain.Entities.Auth.User", b =>
                {
                    b.Navigation("RefreshTokens");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("Vitalis.Domain.Entities.Billing.Invoice", b =>
                {
                    b.Navigation("Items");

                    b.Navigation("Payments");
                });

            modelBuilder.Entity("Vitalis.Domain.Entities.Clinical.MedicalRecord", b =>
                {
                    b.Navigation("Attachments");

                    b.Navigation("Prescription");

                    b.Navigation("Services");

                    b.Navigation("Vitals");
                });

            modelBuilder.Entity("Vitalis.Domain.Entities.Clinical.MedicalRecordService", b =>
                {
                    b.Navigation("LabResults");
                });

            modelBuilder.Entity("Vitalis.Domain.Entities.Clinical.Medicine", b =>
                {
                    b.Navigation("Batches");
                });

            modelBuilder.Entity("Vitalis.Domain.Entities.Clinical.Prescription", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("Vitalis.Domain.Entities.Scheduling.Appointment", b =>
                {
                    b.Navigation("StatusHistory");
                });

            modelBuilder.Entity("Vitalis.Domain.Entities.Scheduling.Doctor", b =>
                {
                    b.Navigation("Schedules");
                });

            modelBuilder.Entity("Vitalis.Domain.Entities.Scheduling.Patient", b =>
                {
                    b.Navigation("Allergies");

                    b.Navigation("InsurancePolicies");
                });

            modelBuilder.Entity("Vitalis.Domain.Entities.Scheduling.Specialty", b =>
                {
                    b.Navigation("Doctors");
                });
#pragma warning restore 612, 618
        }
    }
}
